# Development Environment Properties
# These properties are applied ONLY when the 'dev' profile is active.
# It overrides properties in application.properties

# Example: Local development settings
logging.level.com.jayandhan.portfolio=TRACE
