# Production Environment Properties
# These properties are applied ONLY when the 'prod' profile is active.
# It overrides properties in application.properties

# Example: Production specific security or performance settings
logging.level.com.jayandhan.portfolio=INFO
